- hosts: localhost
  become: yes
  tasks:
  - name: "install nginx"
    apt:
      name: ['nginx']
      state: latest
  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted